import type { ReviewResult } from "@/lib/analysis/review-engine";

export function generateDossierMarkdown(
  review: ReviewResult,
  contractLabel: string
): string {
  const now = new Date().toISOString();
  const driftFindings = review.findings.filter((f) => f.type === "drift");
  const blastFindings = review.findings.filter(
    (f) => f.type === "blast_radius"
  );

  const reqLines = review.contractCoverage.requirements
    .map((r) => `- [${r.satisfied ? "x" : " "}] ${r.text}`)
    .join("\n");

  const findingLines = driftFindings
    .map(
      (f) => `
### ${f.severity.toUpperCase()}: ${f.title}

**File:** \`${f.filePath ?? "N/A"}\`${f.lineNumber ? ` (line ${f.lineNumber})` : ""}
**Rule:** ${f.rule ?? "N/A"}

**Design Intent:** ${f.intent ?? "N/A"}

**Actual Implementation:** ${f.actual ?? f.description}

**Why This Matters:** ${f.whyItMatters ?? f.description}

**Suggested Fix:** ${f.suggestion ?? "See architecture proposal."}
`
    )
    .join("\n---\n");

  const blastLines = review.blastRadius.affectedFiles
    .map(
      (f) => `
### ${f.risk.toUpperCase()} RISK: \`${f.path}\`

${f.unmodified ? "⚠️ **This file was NOT modified in the Pull Request.**\n\n" : ""}**Reason:** ${f.reason}
${f.lineRef ? `\n**Reference:** ${f.lineRef}` : ""}
`
    )
    .join("\n");

  const verLines = review.verification.results
    .map(
      (v) =>
        `- [${v.status === "pass" ? "x" : " "}] ${v.name}${v.reason ? ` — ${v.reason}` : ""}`
    )
    .join("\n");

  return `# IntentLoop Review Dossier

**Generated:** ${now}
**Feature:** ${contractLabel}
**PR:** #${review.prNumber} — ${review.prTitle}
**Intent Alignment:** ${review.intentAlignment}%

---

## Summary

${review.summary}

---

## Architectural Contract

**Feature:** ${contractLabel}

### Requirements

${reqLines}

**Contract Coverage:** ${review.contractCoverage.satisfied} / ${review.contractCoverage.total} requirements satisfied

---

## Intent Drift Findings

${findingLines}

---

## Blast Radius Analysis

**Unmodified files at risk:** ${review.blastRadius.unmodifiedFilesAtRisk}

${blastLines}

---

## Verification Results

${verLines}

---

## Architecture: Expected vs Actual

### Expected

\`\`\`mermaid
${review.architectureComparison.expectedDiagram}
\`\`\`

### Actual

\`\`\`mermaid
${review.architectureComparison.actualDiagram}
\`\`\`

---

## Recommended Remediation

${review.findings
  .filter((f) => f.suggestion)
  .map(
    (f) => `### ${f.title}

${f.suggestion}
`
  )
  .join("\n")}

---

*Generated by Bob IntentLoop*
`;
}
